# .github/actions/ollama-code-review/action.yml
name: "Ollama Code Review"
description: "Generate a code-review with Ollama and print it to the log"

inputs:
  llm-model:
    description: "Model identifier to pass to 'ollama run'"
    required: false
    default: "deepseek-r1:1.5b"

runs:
  using: "composite"
  steps:
    - name: Install Ollama CLI
      shell: bash
      run: |
        curl -fsSL https://ollama.com/install.sh | sh
        ollama --version

    - name: Generate review with Ollama
      shell: bash
      env:
        MODEL: ${{ inputs.llm-model }}
      run: |
        git fetch --quiet origin ${{ github.base_ref || 'main' }}
        git diff origin/${{ github.base_ref || 'main' }} > diff.patch
        echo "=== Running \`ollama run $MODEL\` ==="
        ollama run "$MODEL" < diff.patch > review.txt || true
        echo "=== Review output ==="
        cat review.txt