name: Auto Bump and Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bump-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Generate yarn.lock
        run: yarn import

      - name: Install dependencies with Yarn
        run: yarn install

      - name: Bump version and publish
        id: bump_publish
        run: |
          yarn version --patch --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Publish package
        run: |
          yarn npm publish --access public
