name: Daily Gemini 2.0 Flash Enhancement

on:
  schedule:
    # ogni giorno a mezzanotte UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  daily-enhance:
    runs-on: ubuntu-latest

    steps:
    # 1) checkout del repo
    - uses: actions/checkout@v3

    # 2) install GitHub Copilot CLI extension
    - name: Install Copilot CLI extension
      run: gh extension install github/copilot-cli

    # 3) Generate and apply patch via Copilot CLI
    - name: Generate and apply patch via Copilot CLI
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh copilot patch . --model gemini-2.0-flash --apply --yes

    # 6) committa e pusha se ci sono cambiamenti
    - name: Commit & push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        if ! git diff --cached --exit-code; then
          git commit -m "feat: daily enhancement via Gemini 2.0 Flash"
          git push
        else
          echo "Nessuna modifica da committare."
        fi