name: Daily Gemini 2.0 Flash Enhancement

on:
  schedule:
    # ogni giorno a mezzanotte UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  daily-enhance:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    steps:
    # 1) checkout del repo
    - uses: actions/checkout@v3

    # 2) Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # 3) Install dependencies
    - name: Install dependencies
      run: pip install llama-cpp-python unidiff

    # 4) Download local LLM model
    - name: Download LLM model
      run: |
        mkdir -p models
        curl -L https://huggingface.co/nomic-ai/gpt4all-lora/resolve/main/gpt4all-lora-quantized.bin -o models/gpt4all-lora-quantized.bin

    # 5) Generate and apply patch via local LLM
    - name: Generate and apply patch via local LLM
      run: |
        python - << 'EOF'
        import subprocess
        from llama_cpp import Llama
        llm = Llama(model_path="models/gpt4all-lora-quantized.bin", n_threads=4)
        prompt = "Applica una modifica al codice del progetto per introdurre un piccolo miglioramento/feature. Restituisci un unified diff."
        resp = llm(prompt, max_tokens=1024)
        patch = resp['choices'][0]['text']
        with open("daily.patch", "w") as f: f.write(patch)
        subprocess.run(["git", "apply", "daily.patch"], check=True)
        EOF


    # 6) committa e pusha se ci sono cambiamenti
    - name: Commit & push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        if ! git diff --cached --exit-code; then
          git commit -m "feat: daily enhancement via Gemini 2.0 Flash"
          git push
        else
          echo "Nessuna modifica da committare."
        fi