name: Daily Gemini 2.0 Flash Enhancement

on:
  schedule:
    # ogni giorno a mezzanotte UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  daily-enhance:
    runs-on: ubuntu-latest

    steps:
    # 1) checkout del repo
    - uses: actions/checkout@v3

    # 2) setup di Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # 3) installa dipendenze Python
    - name: Install dependencies
      run: pip install openai

    # 4) genera e applica la patch con script Python
    - name: Generate and apply patch with Python
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python scripts/generate_feature.py

    # 6) committa e pusha se ci sono cambiamenti
    - name: Commit & push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        if ! git diff --cached --exit-code; then
          git commit -m "feat: daily enhancement via Gemini 2.0 Flash"
          git push
        else
          echo "Nessuna modifica da committare."
        fi