name: Daily Gemini 2.0 Flash Enhancement

on:
  schedule:
    # ogni giorno a mezzanotte UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  daily-enhance:
    runs-on: ubuntu-latest

    steps:
    # 1) checkout del repo
    - uses: actions/checkout@v3

    # 2) setup Node.js for Open Codex CLI
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 3) install Open Codex CLI
    - name: Install Open Codex CLI
      run: npm install -g open-codex

    # 4) genera e applica la patch con Open Codex CLI via Gemini 2.0 Flash
    - name: Generate and apply patch via Open Codex CLI
      env:
        GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        open-codex --provider gemini --model gemini-2.0-flash -a auto-edit -q "Applica una modifica al codice del progetto per introdurre un piccolo miglioramento/feature."

    # 6) committa e pusha se ci sono cambiamenti
    - name: Commit & push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        if ! git diff --cached --exit-code; then
          git commit -m "feat: daily enhancement via Gemini 2.0 Flash"
          git push
        else
          echo "Nessuna modifica da committare."
        fi