name: Daily Gemini 2.0 Flash Enhancement

on:
  schedule:
    # ogni giorno a mezzanotte UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  daily-enhance:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}
    steps:
      # 1) checkout del repo
      - uses: actions/checkout@v3

      # 2) Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Install dependencies
      - name: Install dependencies
        run: pip install gpt4all unidiff

      # 4) Generate and apply patch via local GPT4All client
      - name: Generate and apply patch via local GPT4All client
        run: |
          python - << 'EOF'
          import subprocess
          from gpt4all import GPT4All
          # load the model from a local file without downloading
          model = GPT4All(model_name="gpt4all-lora-quantized", model_path="models/gpt4all-lora-quantized.bin", allow_download=False)
          prompt = "Applica una modifica al codice del progetto per introdurre un piccolo miglioramento/feature. Restituisci un unified diff."
          resp = model.generate(prompt)
          patch = resp.strip()
          with open("daily.patch", "w") as f:
              f.write(patch)
          subprocess.run(["git", "apply", "daily.patch"], check=True)
          EOF

      # 5) committa e pusha se ci sono cambiamenti
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --exit-code; then
            git commit -m "feat: daily enhancement via Gemini 2.0 Flash"
            git push
          else
            echo "Nessuna modifica da committare."
          fi
