name: Daily Gemini 2.0 Flash Enhancement

on:
  schedule:
    # ogni giorno a mezzanotte UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  daily-enhance:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    steps:
    # 1) checkout del repo
    - uses: actions/checkout@v3

    # 2) Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # 3) Install dependencies
    - name: Install dependencies
      run: pip install openai==0.28.0

    # 4) Generate and apply patch via Gemini 2.0 Flash
    - name: Generate and apply patch via Gemini 2.0 Flash
      env:
        OPENAI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        python - << 'EOF'
        import os, subprocess, openai
        openai.api_key = os.getenv("OPENAI_API_KEY")
        prompt = "Applica una modifica al codice del progetto per introdurre un piccolo miglioramento/feature. Restituisci un unified diff."
        resp = openai.ChatCompletion.create(
          model="gemini-2.0-flash",
          messages=[{"role":"user","content":prompt}],
          temperature=0.7
        )
        patch = resp.choices[0].message.content
        with open("daily.patch", "w") as f: f.write(patch)
        subprocess.run(["git","apply","daily.patch"], check=True)
        EOF

    # 6) committa e pusha se ci sono cambiamenti
    - name: Commit & push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        if ! git diff --cached --exit-code; then
          git commit -m "feat: daily enhancement via Gemini 2.0 Flash"
          git push
        else
          echo "Nessuna modifica da committare."
        fi