name: Auto Version Bump and Commit Loop

permissions:
  contents: write

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

concurrency:
  group: auto-version-bump
  cancel-in-progress: false

jobs:
  bump-version-loop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Continuous version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          npm version patch --no-git-tag-version
          git add package.json
          VERSION=$(node -p "require('./package.json').version")
          git commit -m "chore: bump version to $VERSION"
          git push origin HEAD:main

      - name: Trigger next workflow run
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'github-auto-publish.yml',
              ref: 'main'
            })