name: "🛡️ Super-Linter"

on:
  push:
    branches:
      - main
  schedule:
      - cron: '0 * * * *'
  pull_request:
    branches:
      - main

jobs:
  super-lint:
    name: Super-Linter
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout del codice
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup di Node.js (per linter JS/TS)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Esegui Super-Linter
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          # Abilita i linters desiderati
          VALIDATE_JS: true
          VALIDATE_TS: true
          # Disabilita gli altri se non ti servono
          VALIDATE_PYTHON: false
          VALIDATE_YAML: true
          # Configurazioni aggiuntive
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}