name: Small Improvement Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  label-small-improvement:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch base branch
        if: github.event_name == 'pull_request'
        run: |
          git fetch --no-tags --depth=1 origin ${{ github.event.pull_request.base.ref }}
      - name: Get changed files
        id: files
        if: github.event_name == 'pull_request'
        run: |
          echo "CHANGED_FILES=$(git diff --name-only FETCH_HEAD...${{ github.event.pull_request.head.sha }})" >> $GITHUB_ENV
      - name: Check for docs or small changes
        id: check
        if: github.event_name == 'pull_request'
        run: |
          DOCS_CHANGED=false
          SMALL_CHANGE=false
          for file in $CHANGED_FILES; do
            if [[ $file == *.md ]]; then
              DOCS_CHANGED=true
            fi
          done
          # Count total lines changed
          LINES_CHANGED=$(git diff --shortstat FETCH_HEAD...${{ github.event.pull_request.head.sha }} | awk '{print ($4+$6)}')
          if [[ $LINES_CHANGED -le 20 ]]; then
            SMALL_CHANGE=true
          fi
          echo "docs=$DOCS_CHANGED" >> $GITHUB_OUTPUT
          echo "small=$SMALL_CHANGE" >> $GITHUB_OUTPUT
      - name: Add label for docs
        if: github.event_name == 'pull_request' && steps.check.outputs.docs == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: docs
      - name: Add label for small improvement
        if: github.event_name == 'pull_request' && steps.check.outputs.small == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: small-improvement
