name: Ollama
'on':
  workflow_dispatch:
jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
    - name: Install ollama
      run: curl -fsSL https://ollama.com/install.sh | sh
    - name: Run ollama
      run: |
        ollama serve &
        ollama pull phi3:mini
    - name: Call ollama API
      run: |
          curl -s --show-error \
          -d '{"model":"phi3:mini","stream":false,"prompt":"What is 2 + 2?"}' \
          http://localhost:11434/api/generate